In [1]:
import pandas as pd
import numpy as np
from scipy.io import loadmat as loadmat
import os
import matplotlib.pyplot as plt
from tqdm import tqdm
import warnings
import matplotlib
matplotlib.rcParams['font.sans-serif'] = ['SimHei']
matplotlib.rcParams['font.family'] = 'sans-serif'
matplotlib.rcParams['axes.unicode_minus'] = False

# Suppress warnings`
warnings.filterwarnings("ignore")

In [2]:
import imp

In [3]:
import xy

In [6]:
xy.IndexMin1000jq.dropna()

,open,close,high,low,volume,money
2014-10-17 9:31,6118.98,6123.02,6123.02,6118.98,219690500.0,2.559234e+09
2014-10-17 9:32,6123.57,6128.08,6128.08,6123.57,80196100.0,9.716844e+08
2014-10-17 9:33,6129.49,6133.54,6133.54,6129.49,70597800.0,8.445222e+08
2014-10-17 9:34,6133.26,6136.48,6136.48,6133.26,75299100.0,8.990858e+08
2014-10-17 9:35,6136.76,6137.24,6137.55,6136.76,77540900.0,9.267430e+08
...,...,...,...,...,...,...
2023-08-04 14:56,6536.42,6536.45,6536.62,6535.71,119264300.0,1.292620e+09
2023-08-04 14:57,6536.46,6536.11,6536.61,6535.84,128617700.0,1.350142e+09
2023-08-04 14:58,6536.15,6536.43,6536.43,6536.15,10438300.0,1.224806e+08
2023-08-04 14:59,6536.43,6536.43,6536.43,6536.43,0.0,0.000000e+00
2023-08-04 15:00,6536.43,6535.32,6536.43,6535.32,215800200.0,2.253315e+09